import {
  errorSchema,
  addStoreParamsSchema,
  storeParamsSchema,
  equipmentSchema,
  menuSchema,
  menuConfigsSchema,
  addMenuSchema,
  addMenuConfigsSchema,
  groupSchema,
  addGroupSchema,
  addRecipeSchema,
  recipeSchema,
  deleteRecipeSchema,
  addRecipeCmaxSchema,
  recipeCmaxSchema,
  deleteRecipeCmaxSchema,
  cookbookSchema,
  deleteCookbookSchema,
  addStepSpeedOvenParamsSchema,
  addStepCombiOvenTSIParamsSchema,
  addStepCombiOvenCMAXParamsSchema,
  addEquipmentRequestSchema,
  addEquipmentResponseSchema
} from './schemas/'

export default {
  error: errorSchema,
  addStore: addStoreParamsSchema,
  store: storeParamsSchema,
  equipment: equipmentSchema,
  addEquipmentRequest: addEquipmentRequestSchema,
  addEquipmentResponse: addEquipmentResponseSchema,
  addMenu: addMenuSchema,
  addMenuConfigs: addMenuConfigsSchema,
  addGroup: addGroupSchema,
  addRecipe: addRecipeSchema,
  addRecipeCmax: addRecipeCmaxSchema,
  deleteRecipeCmax: deleteRecipeCmaxSchema,
  deleteRecipe: deleteRecipeSchema,
  menu: menuSchema,
  menuConfigs: menuConfigsSchema,
  group: groupSchema,
  recipe: recipeSchema,
  recipeCmax: recipeCmaxSchema,
  cookbook: cookbookSchema,
  deleteCookbook: deleteCookbookSchema,
  addStepSpeedOven: addStepSpeedOvenParamsSchema,
  addStepCombiOvenTSI: addStepCombiOvenTSIParamsSchema,
  addStepCombiOvenCMAX: addStepCombiOvenCMAXParamsSchema
}
