export interface LoadMenuConfigsModel {
    id: number,
    equipTypeId: number,
    companyId: number,
    menuName: string,
    creationDate: string,
    lastUpdate: string,
    menuVersion: number,
    deletionDate: string,
    userId: number,
    deletedBy: string,
    language: string,
    configs?: {
        id: number,
        menuId: number,
        preHeat1: number,
        preHeat2: number,
        preHeat2Enabled: boolean,
        stabilizationTime: number,
        dateFormat: string,
        timeFormat: string,
        manualModeEnabled: boolean,
        favoritesEnabled: boolean,
        repeatRecipeEnabled: boolean,
        heatBrownMoreEnabled: boolean,
        temperatureUnit: string,
        weightUnit: string,
        theme: string,
        introduction: boolean,
        combiOvenEnabled: boolean,
        multipleCookingEnabled: boolean,
        technicookRecipesEnabled: boolean,
        editGroupsEnabled: boolean,
        operatorModeEnabled: boolean
    }
}
