export interface RecipeCookbookModel {
    id?: number,
    equipTypeId: number,
    recipeName: string,
    recipeImage: string,
    creationDate: string,
    createdBy: number,
    lastUpdate: string,
    updatedBy: number,
    ingredientType: number,
    dishType: number,
    ingredients: string,
    instructions: string,
    weight: number,
    entryTemp: number,
    companyId: number,
    menuId: number,
    language: number,
    origin: string,
    preHeatTemp: number
}
